/// Lista das raças mais comuns de pets disponíveis para adoção.
/// O campo de raça é um autocomplete: o usuário pode escolher uma destas
/// sugestões OU digitar livremente uma raça que não esteja na lista.
const List<String> kPetBreeds = [
  // ── Cachorros — raças comuns no Brasil ──────────────────────────────
  'SRD (Sem Raça Definida)',
  'Vira-lata Caramelo',
  'Akita',
  'Basset Hound',
  'Beagle',
  'Border Collie',
  'Boxer',
  'Buldogue Francês',
  'Buldogue Inglês',
  'Chihuahua',
  'Chow Chow',
  'Cocker Spaniel',
  'Corgi',
  'Dachshund (Salsicha)',
  'Dálmata',
  'Doberman',
  'Dogo Argentino',
  'Dogue Alemão',
  'Fila Brasileiro',
  'Golden Retriever',
  'Husky Siberiano',
  'Jack Russell Terrier',
  'Labrador',
  'Lhasa Apso',
  'Maltês',
  'Mastim Inglês',
  'Pastor Alemão',
  'Pastor Australiano',
  'Pastor Belga',
  'Pequinês',
  'Pinscher',
  'Pit Bull',
  'Poodle',
  'Pug',
  'Rottweiler',
  'Samoieda',
  'Schnauzer',
  'Shar-Pei',
  'Shiba Inu',
  'Shih Tzu',
  'Spitz Alemão (Lulu da Pomerânia)',
  'Staffordshire Bull Terrier',
  'Weimaraner',
  'Yorkshire',

  // ── Gatos — raças comuns no Brasil ──────────────────────────────────
  'Gato Sem Raça Definida',
  'Abissínio',
  'American Shorthair',
  'Angorá',
  'Bengal',
  'Birmanês',
  'Bombaim',
  'British Shorthair',
  'Burmês',
  'Devon Rex',
  'Exótico',
  'Himalaio',
  'Maine Coon',
  'Manx',
  'Munchkin',
  'Norueguês da Floresta',
  'Oriental',
  'Persa',
  'Ragdoll',
  'Russian Blue',
  'Sagrado da Birmânia',
  'Savannah',
  'Scottish Fold',
  'Siamês',
  'Siberiano',
  'Singapura',
  'Snowshoe',
  'Sphynx',
  'Tonkinês',
  'Turco Van',

  // ── Outros — aves, répteis e exóticos ───────────────────────────────
  'Calopsita',
  'Periquito',
  'Canário',
  'Papagaio',
  'Agapornis',
  'Iguana',
  'Jabuti',
  'Tartaruga',
  'Coelho',
  'Hamster',
  'Porquinho-da-índia',
  'Chinchila',
];
